#!/bin/sh

export PCACHE="$HOME/.cache/vifm/thumbnail.$(
  stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$PWD/$6")" |
    sha256sum | awk '{print $1}'
  )"

  MPV_SOCKET="/tmp/vifm-mpv-preview.sock"

  pclear() {
    printf '{"action": "remove", "identifier": "vifm-preview"}\n' > "$FIFO_UEBERZUG"

    # Kill old mpv safely
    if [ -S "$MPV_SOCKET" ]; then
      printf '{ "command": ["quit"] }\n' | socat - UNIX-CONNECT:"$MPV_SOCKET" 2>/dev/null
      rm -f "$MPV_SOCKET"
    fi
  }

image() {
  printf '{"action": "add", "identifier": "vifm-preview", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' \
    "$2" "$3" "$4" "$5" "$6" > "$FIFO_UEBERZUG"
  }


main() {
  case "$1" in
    "clear")
      pclear
      ;;
    "draw")
      FILE="$PWD/$6"
      image "$1" "$2" "$3" "$4" "$5" "$FILE"
      ;;
    "video")
      ANIM_CACHE="${PCACHE}.gif"
      if [ ! -f "$ANIM_CACHE" ]; then
	ffmpeg -hide_banner -loglevel error \
	  -ss 0 -t 4 -i "$6" \
	  -vf "fps=12,scale=320:-1:flags=lanczos" \
	  "$ANIM_CACHE"
      fi
      image "$1" "$2" "$3" "$4" "$5" "$ANIM_CACHE"
      ;;
    "epub")
      [ ! -f "$PCACHE" ] && epub-thumbnailer "$6" "$PCACHE" 1024
      image "$1" "$2" "$3" "$4" "$5" "$PCACHE"
      ;;
    "pdf")
      [ ! -f "${PCACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$6" "$PCACHE"
      image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
      ;;
    "djvu")
      [ ! -f "${PCACHE}.jpg" ] && ddjvu -format=tiff -quality=90 -page=1 "$6" "$PCACHE.jpg"
      image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
      ;;
    "audio")
      [ ! -f "${PCACHE}.jpg" ] && ffmpeg -hide_banner -i "$6" "${PCACHE}.jpg" -y >/dev/null
      image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
      ;;
    "font")
      [ ! -f "${PCACHE}.jpg" ] && fontpreview -i "$6" -o "${PCACHE}.jpg"
      image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
      ;;
    *)
      ;;
  esac
}

main "$@"

